title: "Daphne Blakey"
description: ""
url: "https://daphneblakey.github.io"

theme: jekyll-theme-minimal
permalink: pretty

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "Daphne Blakey"
