# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Daphne Blakey
tagline:          ''
#description:      'PhD Student, Cornell University' 
url:              "https://daphneblakey.github.io"
baseurl:          "/daphneblakey"


paginate:         5

# Custom vars
#version:          0.0.0

github:
  repo:           https://github.com/daphneblakey/daphneblakey/
