title: "Daphne Blakey"
description: "Quantitative public policy researcher specializing in applied economics, data analysis, and public sector institutions."
tagline: "Interdisciplinary policy research and data analysis."
url: "https://daphneblakey.com"
baseurl: ""      

theme: jekyll-theme-minimal
permalink: pretty

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "Daphne Blakey"

google_analytics: "G-T1MTQJQ9NB"
