title: "Daphne Blakey"
description: "Policy research and data analysis."
url: "https://daphneblakey.github.io"

theme: jekyll-theme-minimal
permalink: pretty

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "Daphne Blakey"

google_analytics: "G-T1MTQJQ9NB"
